"""empty message

Revision ID: b75a06083fbf
Revises: 
Create Date: 2021-12-03 09:02:46.228041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75a06083fbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('status', sa.Enum('Teacher', 'Student'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('course',
    sa.Column('id_course', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('theme', sa.VARCHAR(length=128), nullable=False),
    sa.Column('details', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id_teacher', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_teacher'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_table('request_for_course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_user', sa.INTEGER(), nullable=False),
    sa.Column('id_course', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_course'], ['course.id_course'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_and_course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('id_courses', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_courses'], ['course.id_course'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_and_course')
    op.drop_table('request_for_course')
    op.drop_table('course')
    op.drop_table('user')
    # ### end Alembic commands ###
